import NextAuth from "next-auth";
import { authOptions } from "@/lib/auth-options";

/**
 * NextAuth.js API Route Handler
 *
 * This is the main NextAuth.js API route that handles all authentication requests.
 * It supports the following endpoints:
 *
 * - GET  /api/auth/signin - Sign in page
 * - POST /api/auth/signin/:provider - Initiate OAuth sign in
 * - GET  /api/auth/callback/:provider - OAuth callback
 * - GET  /api/auth/signout - Sign out page
 * - POST /api/auth/signout - Sign out
 * - GET  /api/auth/session - Get session
 * - GET  /api/auth/csrf - Get CSRF token
 * - GET  /api/auth/providers - Get available providers
 *
 * All routes are automatically generated by NextAuth.js based on the configuration
 * in lib/auth-options.ts
 *
 * Security features:
 * - CSRF protection (built-in)
 * - Secure cookies (httpOnly, secure in production)
 * - Rate limiting (implemented in callbacks)
 * - OAuth state validation
 * - Token encryption
 *
 * @see https://next-auth.js.org/configuration/initialization#route-handlers-app
 */
const handler = NextAuth(authOptions);

// Export handlers for both GET and POST requests
export { handler as GET, handler as POST };
